/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/riscv_cpu.v:5.1-150.10" *)
module riscv_cpu(clk, rst);
  (* src = "rtl/riscv_cpu.v:6.16-6.19" *)
  input clk;
  wire clk;
  (* src = "rtl/riscv_cpu.v:7.16-7.19" *)
  input rst;
  wire rst;
endmodule
